ARG FROM_IMAGE_FOR_AR
FROM ${FROM_IMAGE_FOR_AR}

# RUN . $HOME/.cargo/env \
#     && rustup default nightly \
#     && rustup component add miri

RUN sudo apt-get install -y ripgrep vim less

RUN echo "DONE"