#!/usr/bin/env bash
set -e

# Build each image
(cd docker/base         && ../mkimage ar_base           Dockerfile)
(cd docker/solvers      && ../mkimage ar_solvers        Dockerfile)
(cd docker/verifiers    && ../mkimage ar_verifiers      Dockerfile)


docker/mkimage ar docker/ar/Dockerfile
