#lang ivy1.8

include soroban

type key
type val

instance kv: partial_map(key, val)

action _save_restore_roundtrip = {
    kv._save_state();
    kv._restore_state();
    ensure kv.pre(X) = (old kv.pre(X));
    ensure kv.map(X, Y) = (old kv.map(X, Y));
}
export _save_restore_roundtrip

conjecture [succ_lt] ledger.succ(X, Y) -> X:ledger < Y

instance money : integer
conjecture [m_succ_lt] money.succ(X, Y) -> money.lt(X, Y)
conjecture [m_lteq_def]
    forall X:money, Y:money.
        money.lte(X, Y) <-> (money.lt(X, Y) | X = Y)

conjecture [m_lt_irreflexive]
    forall X:money. ~money.lt(X, X)

conjecture [wtf_2] money.lte(money.zero, money.zero)